title = "Hugo Utterances Module"
theme = [
    "github.com/razonyang/hugo-mod-utterances"
]

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
  [languages.zh-hans]
    weight = 2
    languageName = "简体中文"

[params]
  [params.utterances]
    repo = "razonyang/hugo-mod-utterances"
